### ISSUE TITLE
Tools link gives 404

### ISSUE THREAD

**Issue by RandomDude9** [softchris/react-book#194]
https://github.com/softchris/react-book/blob/master/8-tools/storybook.md and https://github.com/softchris/react-book/blob/master/8-tools give a 404 not found error. 

Above links are the ones located on the Table Of Contents on the main page. https://github.com/softchris/react-book

![image](https://user-images.githubusercontent.com/77645956/104968447-fa113700-5a39-11eb-8d76-836034394090.png)

**Comment by softchris** [comment]
thank you, it's now fixed

**Comment by softchris** [comment]
#close
