### ISSUE TITLE
feature: Add a "set up React with webpack and babel" section

### ISSUE THREAD

**Issue by rogeliosamuel621** [softchris/react-book#198]
Hi Chris, I think that you should add a section where you teach how to set up React without create-react-app, It could be difficult for beginners but that can help them to increase their skills, and they will understand how webpack works.

**Comment by softchris** [comment]
hi there.. Appreciate the suggestion. I'll look into it :)

**Comment by softchris** [comment]
#close , it's now implemented in the setup.md file and there's also a solution project for webpack + babel
