### ISSUE TITLE
Remove hyperlinks for titles

### ISSUE THREAD

**Issue by g-savitha** [softchris/react-book#204]
Clicking on titles leads to 404. 

![image](https://user-images.githubusercontent.com/31612459/105383636-51c8c180-5c37-11eb-986e-9f7499be0cb0.png)

![image](https://user-images.githubusercontent.com/31612459/105383878-99e7e400-5c37-11eb-9ef9-959b33fcc34b.png)

Click on basics or styling or any of the headings listed.

**Comment by softchris** [comment]
Thank you for telling me. I'll work on a solution

**Comment by almirleandro** [comment]
That's happening because the headings are linking to their respective folders, which don't have a .md file.

@softchris I can make a pull request removing the link of the headings, at least until a better solution comes up.

**Comment by softchris** [comment]
#208 closing thanks to your PR :) Much appreciated @almirleandro
