### ISSUE TITLE
Translations page leads to a 404 page.

### ISSUE THREAD

**Issue by Accomigt** [softchris/react-book#206]
When you go to TRANSLATIONS.md and try to see how to contribute, it takes you to a 404 page.

![chrome_Pn9kEiJJpV](https://user-images.githubusercontent.com/71159832/105398703-4bf7bf80-5be8-11eb-9612-cb367924d552.png)
![chrome_nYGTysAuNb](https://user-images.githubusercontent.com/71159832/105398732-50bc7380-5be8-11eb-8343-d56a03e008fe.png)

**Comment by softchris** [comment]
Can't repeat, I tried this: 
- Navigate to  https://softchris.github.io/react-book/#/
- Clicking link here: "This book now supports Docsify and really welcomes translations. Check out Translations.md"
- Ends up here https://softchris.github.io/react-book/#/TRANSLATIONS  , that link for me

Can you please verify if this is what you're doing? @Accomigt

**Comment by Accomigt** [comment]
> Can't repeat, I tried this:
> 
> * Navigate to  https://softchris.github.io/react-book/#/
> * Clicking link here: "This book now supports Docsify and really welcomes translations. Check out Translations.md"
> * Ends up here https://softchris.github.io/react-book/#/TRANSLATIONS  , that link for me
> 
> Can you please verify if this is what you're doing? @Accomigt

Mhm, but still, going to where it says *translations*, it sends me to a 404 error.

**Comment by softchris** [comment]
@Accomigt  Are you saying you're clicking on **There are translations folders** cause that gives 404 for me? Just want to verify that we mean the same thing.

**Comment by Accomigt** [comment]
> @Accomigt Are you saying you're clicking on **There are translations folders** cause that gives 404 for me? Just want to verify that we mean the same thing.

Yes.

**Comment by almirleandro** [comment]
@Accomigt  I saw the same issue. Working on that.

**Comment by softchris** [comment]
#207 Thanks @almirleandro closing it now with your PR
